### ISSUE TITLE
KitchenSink app exception on TC build agent

### ISSUE THREAD

**Issue by ghost** [StarcounterApps/KitchenSink#102] opened 2017-03-03 10:44 UTC
On TC build agent first two or three kitchensink app open gets this error

![image](https://cloud.githubusercontent.com/assets/25149662/23548114/50a2d2dc-0006-11e7-8a37-84d4ca6c1ffc.png)

KitchenSink Dev witch v2.3-Nightly-Windows Starcounter

@chrhol Do you know why sometimes this problem occurs?
cc @warpech

**Comment by warpech** [comment] 2017-03-03 11:13
@KmaTTi89 can you also paste the stack trace as text, not only as a screenshot?

**Comment by KmaTTi89** [comment] 2017-03-03 12:19
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.LinkedList`1.InternalRemoveNode(LinkedListNode`1 node)
   at Starcounter.Internal.SchedulerSessions.CreateNewSession(ScSessionStruct& ss, IAppsSession apps_session_int) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Internal\Sessions\InternalSessions.cs:line 534
   at Starcounter.Session..ctor(SessionOptions options, Nullable`1 includeNamespaces) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 98
   at KitchenSink.Program.<>c.<Main>b__0_0() in C:\TeamCity\BuildAgent\work\build-487\KitchenSink\src\KitchenSink\Program.cs:line 27
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 341
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1133
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(String uri) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Internal\Rest\Self.cs:line 74
   at KitchenSink.Program.WrapPage[T](String partialPath) in C:\TeamCity\BuildAgent\work\build-487\KitchenSink\src\KitchenSink\Program.cs:line 265
   at KitchenSink.Program.<>c.<Main>b__0_3() in C:\TeamCity\BuildAgent\work\build-487\KitchenSink\src\KitchenSink\Program.cs:line 40
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 341
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-3159\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
HResult=-2147467261

More information about this error may be available in the server error log.
```

**Comment by warpech** [comment] 2017-03-03 15:08
@chrhol any idea where does this error come from? It shows up randomly just after starting of the app. 2-3 in 100 KitchenSink tests fail because of this randomly on the build agent.

**Comment by chrhol** [comment] 2017-03-03 15:29
I have no idea, I think maybe @alemoi  can answer this one better. Looks like something happens internally when a new Session is created.

**Comment by alemoi** [comment] 2017-03-03 21:47
@KmaTTi89 thanks for reporting! I am looking into it.

**Comment by alemoi** [comment] 2017-03-03 22:12
@KmaTTi89 Does it happen right after KitchenSink app start and opening `http://127.0.0.1:8080/kitchensink/mainpage` in the browser?

**Comment by KmaTTi89** [comment] 2017-03-06 13:55
@alemoi 
Yes, this happen when automated test try to open http://localhost:8080/KitchenSink/MainPage after app is started.

I don't know how to reproduce this in manual way because this is automated test. 
It started to happen when I turn on parallel tests .
So a several browser with this adrress is opened at the same time, maybe this is the problem.

**Comment by alemoi** [comment] 2017-03-06 14:49
Thank you for the answer! How can I run the automated test? Do you have some instructions? Thanks!

**Comment by KmaTTi89** [comment] 2017-03-06 19:41
You have to run kitchensink build (you can run dev) on TC and login to build agent. Just wait about 20 second and tests will start and you will able to see browsers with kitchensink app

**Comment by KmaTTi89** [comment] 2017-03-09 12:24
@alemoi 
Do you need more help with this?

**Comment by warpech** [comment] 2017-03-09 15:31
@alemoi pls help, because it hinders our continues integration for apps. Thanks!

**Comment by alemoi** [comment] 2017-03-09 16:34
I will start the investigation now.

**Comment by alemoi** [comment] 2017-03-09 16:57
> @alemoi pls help, because it hinders our continues integration for apps. Thanks!

Can you explain how exactly so I can tackle the problem faster?

> You have to run kitchensink build (you can run dev) on TC and login to build agent. Just wait about 20 second and tests will start and you will able to see browsers with kitchensink app

Can I observe this error somewhere in the build log? Like this: https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=20638#_focus=394

I just need a consistent way to verify if the problem is fixed.

**Comment by warpech** [comment] 2017-03-09 21:04
> Can you explain how exactly so I can tackle the problem faster? Do you have failing builds because of this? These? https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_KitchenSinkTestsDevelop&branch_Starcounter_Apps_KitchenSink=%3Cdefault%3E&tab=buildTypeStatusDiv

Yes. Locally 100% tests are passing. On the build server, from 1 to 3 tests are failing in each build.

> Can I observe this error somewhere in the build log? Like this: https://teamcity.starcounter.org/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=20638#_focus=394

Yes, this is how that error is logged in TeamCity, because Selenium is looking for some HTML elements on a page but all it can see is the text stack trace.

On the build agent, a screenshot is made in TC working directory at the moment when the error occurs. Also, the exception should be available in Starcounter log.

Sadly, I cannot access ScBuildAppWin01 in the new VPN (any idea why?), so I cannot provide more precise instructions right now.

> I just need a consistent way to verify if the problem is fixed.

When the problem is fixed, 100% of the tests in https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_KitchenSinkTestsDevelop will pass.

**Comment by alemoi** [comment] 2017-03-09 21:08
> When the problem is fixed, 100% of the tests in https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_KitchenSinkTestsDevelop will pass.

Thanks for the clarification. Im working on it now.

**Comment by warpech** [comment] 2017-03-09 21:29
The problem might be related to the fact that https://github.com/StarcounterApps/KitchenSink/commit/63baa69b054b92e35179dad556673d983329c354 added parallel execution of Selenium tests. This means that after the app is started, Selenium triggers multiple browser windows simultaneously.

To verify, you can compare running builds from that commit and the previous one (https://github.com/StarcounterApps/KitchenSink/commit/d9417ded1a1db7c10477807f22408db79bbe2d3c).

**Comment by alemoi** [comment] 2017-03-10 12:40
Then its an awesome test, which we should definitely address.

**Comment by alemoi** [comment] 2017-03-10 13:31
I now changed to grab artifacts from my fixing branch and it seems to succeed with it: https://teamcity.starcounter.org/viewType.html?buildTypeId=Apps_KitchenSinkTestsDevelop&branch_Starcounter_Apps_KitchenSink=%3Cdefault%3E&tab=buildTypeStatusDiv

**Comment by warpech** [comment] 2017-03-10 13:36
Can you explain? I can't see anything successful there:

<img width="1406" alt="screen shot 2017-03-10 at 14 35 56" src="https://cloud.githubusercontent.com/assets/566463/23797195/e4eedbfa-059e-11e7-8139-dbca2b57a10e.png">

**Comment by alemoi** [comment] 2017-03-10 13:37
Click on History tab :)

**Comment by warpech** [comment] 2017-03-10 13:39
The History tab shows only *my* personal builds :( Can I change that?

**Comment by warpech** [comment] 2017-03-10 13:40
I can see it here: https://teamcity.starcounter.org/agentDetails.html?id=8&tab=agentHistory

**Comment by alemoi** [comment] 2017-03-10 13:40
Yes, in your settings: 
![image](https://cloud.githubusercontent.com/assets/208134/23797313/8e587106-059f-11e7-83cc-299e1a4db14a.png)

**Comment by warpech** [comment] 2017-03-10 13:41
Thanks! So why does it work now, has you changed anything?

**Comment by alemoi** [comment] 2017-03-10 13:43
Yes, I made data structures to be lock free, even if they are running on different schedulers. Its part of the general problem with scheduling that we have.

**Comment by warpech** [comment] 2017-03-10 14:04
Wow, then I am happy that the tests helped to find a bug in the schedulers!

**Comment by KmaTTi89** [comment] 2017-03-10 14:05
👍

**Comment by alemoi** [comment] 2017-03-10 19:45
Guys, I just pushed the fix. Hopefully it will work for all cases. Lets monitor this for a while and then close the issue, if sufficient.

**Comment by alemoi** [comment] 2017-03-11 13:16
When I now run against latest nightly, the problem occurs again, but never on personal build with other artifacts. Mystics!

**Comment by alemoi** [comment] 2017-03-11 17:47
@KmaTTi89 @warpech how can I see what is the error now? Can you please guys help out a bit? Thanks!

**Comment by KmaTTi89** [comment] 2017-03-13 09:33
@alemoi 
You can ask me for help on Slack :)

**Comment by alemoi** [comment] 2017-03-13 13:44
@KmaTTi89 @warpech do you use slack for communication in your team?
I'm just trying to understand what's the error now, after I pushed the fix. Interestingly, when I ran personal builds I got 100% success rate... that's why its very weird.

**Comment by KmaTTi89** [comment] 2017-03-13 14:05
@alemoi You can ping me on hangouts: krystianmatti@gmail.com

**Comment by warpech** [comment] 2017-03-14 10:15
> @KmaTTi89 @warpech do you use slack for communication in your team?

Yes, I have invited you if you want to give it a try. Basically it is awesome except it does not have screen-sharing.

Any progress on this? It is urgent, because we want to continue adding more apps to TC. Thanks!

**Comment by KmaTTi89** [comment] 2017-03-14 10:18
I think problem with exceptions is gone. I added pull request with fix for starcounter 2.3

**Comment by alemoi** [comment] 2017-03-14 13:15
@KmaTTi89 can you please briefly describe what were the latest problems with the build?

**Comment by KmaTTi89** [comment] 2017-03-14 13:19
@alemoi New Starcounter version 2.3 added shadow root for two pages in Kitchensink. Tests weren't prepared for this. Fixed already.

**Comment by alemoi** [comment] 2017-03-14 13:23
Thanks! Closing the issue.

**Comment by KmaTTi89** [comment] 2017-03-21 12:56
I need to reopen this issue because bug came back on master branch with starcounter 2.3 nightly

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.LinkedList`1.InternalRemoveNode(LinkedListNode`1 node)
   at Starcounter.Internal.SchedulerSessions.CreateNewSession(ScSessionStruct& ss, IAppsSession apps_session_int) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Internal\Sessions\InternalSessions.cs:line 534
   at Starcounter.Session..ctor(SessionOptions options, Nullable`1 includeNamespaces) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 110
   at KitchenSink.Program.<>c.<Main>b__0_0() in C:\TeamCity\BuildAgent\work\build-30\KitchenSink\src\KitchenSink\Program.cs:line 27
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Rest.UriManagedHandlersCodegen.RunUriMatcherAndCallHandler(String methodSpaceUriSpace, String methodSpaceUriSpaceLower, Request req, UInt16 portNumber, Response& resp) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 1117
   at Starcounter.Self.DoSelfCall(UInt16 portNumber, String method, String relativeUri, Dictionary`2 headersDictionary, String body, Byte[] bodyBytes, HandlerOptions handlerOptions, Request req) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Internal\Rest\Self.cs:line 397
   at Starcounter.Self.GET(String uri) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Internal\Rest\Self.cs:line 74
   at KitchenSink.Program.WrapPage[T](String partialPath) in C:\TeamCity\BuildAgent\work\build-30\KitchenSink\src\KitchenSink\Program.cs:line 265
   at KitchenSink.Program.<>c.<Main>b__0_3() in C:\TeamCity\BuildAgent\work\build-30\KitchenSink\src\KitchenSink\Program.cs:line 40
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 221
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-3838\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
HResult=-2147467261

More information about this error may be available in the server error log.
```

**Comment by alemoi** [comment] 2017-03-21 14:12
@KmaTTi89 thanks for reporting! Can you please point to the build in TeamCity? I would like to know which nightly version was it.

**Comment by KmaTTi89** [comment] 2017-03-22 08:13
@alemoi Please take a look at the last 4 builds:
[#30](http://teamcity.starcounter.org/viewLog.html?buildId=21570&tab=buildResultsDiv&buildTypeId=Apps_KitchenSink_Master)
[#29](http://teamcity.starcounter.org/viewLog.html?buildId=21499&tab=buildResultsDiv&buildTypeId=Apps_KitchenSink_Master)
[#28](http://teamcity.starcounter.org/viewLog.html?buildId=21498&tab=buildResultsDiv&buildTypeId=Apps_KitchenSink_Master)
[#27](http://teamcity.starcounter.org/viewLog.html?buildId=21497&tab=buildResultsDiv&buildTypeId=Apps_KitchenSink_Master)

**Comment by warpech** [comment] 2017-03-29 11:13
<img width="579" alt="screen shot 2017-03-29 at 13 12 42" src="https://cloud.githubusercontent.com/assets/566463/24451981/6e5fb210-1481-11e7-870a-7d08d95613c0.png">

@KmaTTi89 can you pls revert the commit until the `starpack` problem is fixed?

**Comment by KmaTTi89** [comment] 2017-03-29 11:19
@warpech I don't need to revert the commit I will disable deploy step in develop configuration

**Comment by warpech** [comment] 2017-04-13 10:43
Is this solved now?

**Comment by warpech** [comment] 2017-04-20 19:09
Ping @KmaTTi89

**Comment by KmaTTi89** [comment] 2017-04-21 07:54
@warpech 
Make merge dev->master and i will check

**Comment by warpech** [comment] 2017-04-21 08:39
Merged

**Comment by KmaTTi89** [comment] 2017-04-21 08:43
problem still occurs with sc release nightly

**Comment by warpech** [comment] 2017-04-21 08:57
I don't get it, what is the difference between the configurations that the test works in "KitchenSink Develop branch with Starcounter RC nightly" and fails in "KitchenSink Master branch with Starcounter Release nightly"?

**Comment by KmaTTi89** [comment] 2017-04-21 08:59
Starcounter version?

**Comment by warpech** [comment] 2017-04-21 09:16
Ok, let's get back to this when 2.3 stable is released.

**Comment by alemoi** [comment] 2017-08-30 16:56
This problem is probably no longer relevant. Closing.

**Closed by alemoi** 2017-08-30 16:56 UTC
